name: Build Android App Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Build Tools
        run: |
          yes | sdkmanager "platforms;android-35"
          yes | sdkmanager "build-tools;34.0.0"

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Android Platform
        run: cordova platform add android@13.0.0

      - name: Build Android App Bundle (Release)
        run: |
          echo "configurations.all { exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'; exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8' }" >> platforms/android/app/build.gradle
          cordova build android --release -- --packageType=bundle

      - name: Crear Firma Digital (Keystore) y Firmar el Juego
        run: |
          keytool -genkey -v -keystore affter.keystore -alias affter -keyalg RSA -keysize 2048 -validity 10000 -storepass "affter123" -keypass "affter123" -dname "CN=Affter"
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore affter.keystore -storepass "affter123" platforms/android/app/build/outputs/bundle/release/app-release.aab affter

      - name: Subir AAB Firmado (Sube esto a Google Play)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-firmado
          path: platforms/android/app/build/outputs/bundle/release/app-release.aab

      - name: Guardar Llave Maestra (Guarda esto en tu PC)
        uses: actions/upload-artifact@v4
        with:
          name: llave-maestra-affter
          path: affter.keystore
