name: Build Android App Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Android Build Tools
        run: |
          echo "y" | sdkmanager "build-tools;33.0.2"

      - name: Add Android Platform
        run: cordova platform add android@12.0.1

      - name: Build Android App Bundle (Release)
        run: |
          echo "configurations.all { exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'; exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8' }" >> platforms/android/app/build.gradle
          cordova build android --release -- --packageType=bundle

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: platforms/android/app/build/outputs/bundle/release/app-release.aab
